# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mysql
    container_name: mysql_container
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: devdojo
      MYSQL_DATABASE: devdojo
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer_container
    ports:
      - 8081:8080

volumes:
  db_data: